'use strict'

/**
 * Mig 168 — descripciones de unidades SAT curadas.
 *
 * La mig 167 carga las 2,418 claves de c_ClaveUnidad del XSD oficial con
 * name = code (placeholder, sin descripcion). Esta mig pisa con descripciones
 * legibles para las 166 unidades mas comunes en industria mexicana
 * (las que estaban embebidas en saas-erp-frontend/src/data/satUnits.js).
 *
 * Al hacer ON CONFLICT (code) DO UPDATE, las entradas previamente cargadas
 * con name=code obtienen su nombre real, sin afectar las que ya tenian
 * descripcion del bulk import del Excel oficial cuando llegue.
 *
 * Codigos no oficiales del SAT (ej. MIL = Millar) tambien se cargan aqui.
 * El XSD del SAT no los tiene, pero los aceptamos para uso comercial
 * interno; al timbrar CFDI el cliente debe verificar la equivalencia oficial.
 */

const up = `
  INSERT INTO sat_unit_codes (code, name) VALUES
      ('ACT', 'Actividad'),
      ('E48', 'Unidad de servicio'),
      ('E51', 'Trabajo'),
      ('E52', 'Estación de trabajo'),
      ('KT', 'Kit'),
      ('SET', 'Conjunto'),
      ('11', 'Equipos'),
      ('10', 'Grupos'),
      ('H87', 'Pieza'),
      ('C62', 'Uno (unidad)'),
      ('DPC', 'Docena de piezas'),
      ('14', 'Decenas'),
      ('D14', 'Centena'),
      ('NPR', 'Número de pares'),
      ('PR', 'Par'),
      ('D63', 'Libro'),
      ('D67', 'Dosis'),
      ('EA', 'Cada uno'),
      ('X4', 'Pieza individual'),
      ('KGM', 'Kilogramo'),
      ('GRM', 'Gramo'),
      ('TNE', 'Tonelada métrica'),
      ('MGM', 'Miligramo'),
      ('MC', 'Microgramo'),
      ('LBR', 'Libra'),
      ('ONZ', 'Onza'),
      ('TON', 'Tonelada (larga)'),
      ('HKM', 'Kilogramos por 100 (paquete)'),
      ('CGM', 'Centigramo'),
      ('DG', 'Decigramo'),
      ('KTN', 'Kilotonelada'),
      ('LTR', 'Litro'),
      ('MLT', 'Mililitro'),
      ('DLT', 'Decilitro'),
      ('CLT', 'Centilitro'),
      ('HLT', 'Hectolitro'),
      ('GLI', 'Galón (Reino Unido)'),
      ('GLL', 'Galón (EUA)'),
      ('4G', 'Microlitro'),
      ('KL', 'Kilolitro'),
      ('MTQ', 'Metro cúbico'),
      ('DMQ', 'Decímetro cúbico'),
      ('CMQ', 'Centímetro cúbico'),
      ('MMQ', 'Milímetro cúbico'),
      ('INQ', 'Pulgada cúbica'),
      ('FTQ', 'Pie cúbico'),
      ('YDQ', 'Yarda cúbica'),
      ('5I', 'Mil pies cúbicos estándar'),
      ('MTR', 'Metro'),
      ('CMT', 'Centímetro'),
      ('MMT', 'Milímetro'),
      ('DMT', 'Decímetro'),
      ('KMT', 'Kilómetro'),
      ('INH', 'Pulgada'),
      ('FOT', 'Pie'),
      ('YRD', 'Yarda'),
      ('SMI', 'Milla'),
      ('4H', 'Micrómetro'),
      ('NMI', 'Milla náutica'),
      ('MTK', 'Metro cuadrado'),
      ('CMK', 'Centímetro cuadrado'),
      ('MMK', 'Milímetro cuadrado'),
      ('DMK', 'Decímetro cuadrado'),
      ('KMK', 'Kilómetro cuadrado'),
      ('HAR', 'Hectárea'),
      ('ARE', 'Área'),
      ('INK', 'Pulgada cuadrada'),
      ('FTK', 'Pie cuadrado'),
      ('YDK', 'Yarda cuadrada'),
      ('ACR', 'Acre'),
      ('SEC', 'Segundo'),
      ('MIN', 'Minuto'),
      ('HUR', 'Hora'),
      ('DAY', 'Día'),
      ('WEE', 'Semana'),
      ('MON', 'Mes'),
      ('ANN', 'Año'),
      ('D40', 'Mil segundos'),
      ('HTZ', 'Hertz'),
      ('KHZ', 'Kilohertz'),
      ('MHZ', 'Megahertz'),
      ('GHZ', 'Gigahertz'),
      ('KMH', 'Kilómetro por hora'),
      ('MTS', 'Metro por segundo'),
      ('2M', 'Centímetro por segundo'),
      ('IU', 'Pulgada por segundo'),
      ('FR', 'Pie por segundo'),
      ('KWH', 'Kilowatt hora'),
      ('MWH', 'Megawatt hora'),
      ('GWH', 'Gigawatt hora'),
      ('WHR', 'Watt hora'),
      ('JOU', 'Joule'),
      ('KJO', 'Kilojoule'),
      ('MJ', 'Megajoule'),
      ('KWT', 'Kilowatt'),
      ('MAW', 'Megawatt'),
      ('WTT', 'Watt'),
      ('HP', 'Caballo de potencia'),
      ('BHP', 'Caballo eléctrico'),
      ('AMP', 'Amperio'),
      ('VLT', 'Voltio'),
      ('KVT', 'Kilovoltio'),
      ('KVA', 'Kilovoltio amperio'),
      ('OHM', 'Ohm'),
      ('KO', 'Kiloohm'),
      ('FAR', 'Faradio'),
      ('COU', 'Coulomb'),
      ('2F', 'Kilovar'),
      ('CEL', 'Grado Celsius'),
      ('FAH', 'Grado Fahrenheit'),
      ('KEL', 'Kelvin'),
      ('BAR', 'Bar'),
      ('PAL', 'Pascal'),
      ('KPA', 'Kilopascal'),
      ('MPA', 'Megapascal'),
      ('PSI', 'Libra por pulgada cuadrada'),
      ('ATM', 'Atmósfera estándar'),
      ('MBR', 'Milibar'),
      ('XBX', 'Caja'),
      ('XBA', 'Barril'),
      ('XBC', 'Caja de botellas'),
      ('XBG', 'Bolsa'),
      ('XBJ', 'Cubo'),
      ('XBO', 'Botella'),
      ('XBR', 'Barra'),
      ('XCH', 'Recipiente'),
      ('XCJ', 'Cono'),
      ('XCN', 'Lata'),
      ('XCT', 'Cartón'),
      ('XCS', 'Estuche'),
      ('XDR', 'Tambor'),
      ('XGB', 'Botellón de gas'),
      ('XJR', 'Tarro'),
      ('XKG', 'Saco'),
      ('XPK', 'Paquete'),
      ('XPL', 'Placa'),
      ('XPP', 'Pieza'),
      ('XPU', 'Bandeja'),
      ('XPX', 'Paleta'),
      ('XRO', 'Rollo'),
      ('XSA', 'Saco'),
      ('XSC', 'Costal'),
      ('XSK', 'Esqueleto'),
      ('XSL', 'Lámina'),
      ('XTC', 'Caja de té'),
      ('XTU', 'Tubo'),
      ('XVA', 'Frasco'),
      ('XVI', 'Vial'),
      ('XYT', 'Yute'),
      ('XCR', 'Cajón'),
      ('MGL', 'Miligramo por litro'),
      ('A35', 'Kilogramo por metro cúbico'),
      ('23', 'Gramo por centímetro cúbico'),
      ('TKM', 'Tonelada-kilómetro'),
      ('PA', 'Tira'),
      ('P1', 'Porcentaje'),
      ('BLD', 'Barril seco (US)'),
      ('BLL', 'Barril (US)'),
      ('87', 'Litro por segundo'),
      ('96', 'Litro por minuto'),
      ('PAQ', 'Paquete (no SAT estándar, sólo para compat local)'),
      ('KMQ', 'Kilogramo por metro cuadrado'),
      ('A75', 'Kilometro por kilolitro'),
      ('MIL', 'Millar (uso comercial — verifica equivalencia SAT al timbrar)')
   ON CONFLICT (code) DO UPDATE
     SET name = EXCLUDED.name, updated_at = NOW();
`

const down = `
  -- No-op: revertir significaria reescribir nombres con codigos placeholder.
  SELECT 1;
`

module.exports = { up, down }
